package ve.smile.consume.services;

import ve.smile.seguridad.consume.services.MensajeSistemaService;
import ve.smile.seguridad.consume.services.OperacionService;
import ve.smile.seguridad.consume.services.SclassService;
import ve.smile.seguridad.consume.services.VistaOperacionBasicoService;
import ve.smile.seguridad.consume.services.UsuarioService;
import ve.smile.seguridad.consume.services.PermisoSeguridadService;
import ve.smile.seguridad.consume.services.IconSclassService;
import ve.smile.seguridad.consume.services.VistaOperacionCustomService;
import ve.smile.seguridad.consume.services.TablaService;
import ve.smile.seguridad.consume.services.VistaService;
import ve.smile.seguridad.consume.services.AuditoriaService;
import ve.smile.seguridad.consume.services.SesionService;
import ve.smile.seguridad.consume.services.NodoMenuService;
import ve.smile.seguridad.consume.services.RolService;
import ve.smile.seguridad.consume.services.MetodoDaoService;

public class S {

	// Services Seguridad
	public static VistaOperacionBasicoService VistaOperacionBasicoService;
	public static UsuarioService UsuarioService;
	public static PermisoSeguridadService PermisoSeguridadService;
	public static IconSclassService IconSclassService;
	public static VistaOperacionCustomService VistaOperacionCustomService;
	public static TablaService TablaService;
	public static OperacionService OperacionService;
	public static VistaService VistaService;
	public static AuditoriaService AuditoriaService;
	public static SesionService SesionService;
	public static NodoMenuService NodoMenuService;
	public static RolService RolService;
	public static MetodoDaoService MetodoDaoService;
	public static MensajeSistemaService MensajeSistemaService;
	public static SclassService SclassService;

	// Services Smile
	public static EventPlanPersonaService EventPlanPersonaService;
	public static FortalezaService FortalezaService;
	public static ActividadService ActividadService;
	public static IndicadorTsPlanActividadService IndicadorTsPlanActividadService;
	public static BeneficiarioFamiliarService BeneficiarioFamiliarService;
	public static ComentarioAlbumService ComentarioAlbumService;
	public static ColaboradorService ColaboradorService;
	public static TsPlanService TsPlanService;
	public static ClasificadorCapacitacionService ClasificadorCapacitacionService;
	public static IncidenciaTsPlanService IncidenciaTsPlanService;
	public static ProfesionService ProfesionService;
	public static ClasificadorReconocimientoService ClasificadorReconocimientoService;
	public static ClasificadorMotivoService ClasificadorMotivoService;
	public static RecursoService RecursoService;
	public static DirectorioService DirectorioService;
	public static IndicadorEventoPlanificadoService IndicadorEventoPlanificadoService;
	public static RequisitoService RequisitoService;
	public static CiudadService CiudadService;
	public static EtiqAlbumService EtiqAlbumService;
	public static SolicitudAyudaService SolicitudAyudaService;
	public static TrabajadorService TrabajadorService;
	public static TsPlanActividadRecursoService TsPlanActividadRecursoService;
	public static MultimediaAlbumService MultimediaAlbumService;
	public static VoluntarioFortalezaService VoluntarioFortalezaService;
	public static PreguntaService PreguntaService;
	public static TsPlanActividadService TsPlanActividadService;
	public static ClasificadorVoluntarioService ClasificadorVoluntarioService;
	public static EventoPlanificadoService EventoPlanificadoService;
	public static NotificacionUsuarioService NotificacionUsuarioService;
	public static EventPlanTareaVoluntarioService EventPlanTareaVoluntarioService;
	public static ComentarioCarteleraService ComentarioCarteleraService;
	public static ReconocimientoPersonaService ReconocimientoPersonaService;
	public static RedSocialService RedSocialService;
	public static TsPlanActividadTrabajadorService TsPlanActividadTrabajadorService;
	public static EventoService EventoService;
	public static CargoService CargoService;
	public static ValoresService ValoresService;
	public static IndicadorTsPlanService IndicadorTsPlanService;
	public static TrabajadorProfesionService TrabajadorProfesionService;
	public static ParticipacionService ParticipacionService;
	public static BancoService BancoService;
	public static FamiliarService FamiliarService;
	public static VolCapacitacionPlanificadaService VolCapacitacionPlanificadaService;
	public static TsPlanActividadVoluntarioService TsPlanActividadVoluntarioService;
	public static EventPlanTareaRecursoService EventPlanTareaRecursoService;
	public static AyudaService AyudaService;
	public static EventPlanTareaTrabajadorService EventPlanTareaTrabajadorService;
	public static PublicacionRedSocialService PublicacionRedSocialService;
	public static SolicitudAyudaRecursoService SolicitudAyudaRecursoService;
	public static AlbumService AlbumService;
	public static CapacitacionPlanificadaService CapacitacionPlanificadaService;
	public static RequisitoAyudaService RequisitoAyudaService;
	public static PreguntaClasificadaService PreguntaClasificadaService;
	public static BeneficiarioService BeneficiarioService;
	public static VoluntarioClasificadoService VoluntarioClasificadoService;
	public static UnidadMedidaService UnidadMedidaService;
	public static VoluntarioService VoluntarioService;
	public static TrabajadorFortalezaService TrabajadorFortalezaService;
	public static PadrinoService PadrinoService;
	public static CarteleraService CarteleraService;
	public static RedSocialOrganizacionService RedSocialOrganizacionService;
	public static EtiqCarteleraService EtiqCarteleraService;
	public static VoluntarioProfesionService VoluntarioProfesionService;
	public static OrganizacionService OrganizacionService;
	public static EventPlanTareaService EventPlanTareaService;
	public static MotivoService MotivoService;
	public static IndicadorService IndicadorService;
	public static ClasificadorEventoService ClasificadorEventoService;
	public static TrabajoSocialService TrabajoSocialService;
	public static TareaService TareaService;
	public static PlantillaEventoIndicadorService PlantillaEventoIndicadorService;
	public static ClasificadorTrabajoSocialService ClasificadorTrabajoSocialService;
	public static EventoFavoritoUsuarioService EventoFavoritoUsuarioService;
	public static TsPlanPersonaService TsPlanPersonaService;
	public static RespaldoService RespaldoService;
	public static CapacitacionService CapacitacionService;
	public static ConfiguracionService ConfiguracionService;
	public static ParentescoService ParentescoService;
	public static DonativoRecursoService DonativoRecursoService;
	public static EstudioSocioEconomicoService EstudioSocioEconomicoService;
	public static EtiqTsPlanificadoService EtiqTsPlanificadoService;
	public static CuentaBancariaService CuentaBancariaService;
	public static ClasificadorTareaService ClasificadorTareaService;
	public static PatrocinadorService PatrocinadorService;
	public static PlantillaEventoTareaService PlantillaEventoTareaService;
	public static ClasificadorSugerenciaService ClasificadorSugerenciaService;
	public static RequisitoParticipacionService RequisitoParticipacionService;
	public static DonativoCuentaBancariaService DonativoCuentaBancariaService;
	public static EtiquetaService EtiquetaService;
	public static ComunidadService ComunidadService;
	public static FrecuenciaAporteService FrecuenciaAporteService;
	public static InteraccionPortalService InteraccionPortalService;
	public static ClasificadorActividadService ClasificadorActividadService;
	public static DifusionService DifusionService;
	public static ClasificadorPreguntaService ClasificadorPreguntaService;
	public static IncidenciaEventoPlanService IncidenciaEventoPlanService;
	public static ContactoPortalService ContactoPortalService;
	public static EtiqEventoPlanificadoService EtiqEventoPlanificadoService;
	public static EstadoService EstadoService;
	public static MultimediaService MultimediaService;
	public static IndicadorEventoPlanTareaService IndicadorEventoPlanTareaService;
	public static EventPlanPatrocinadorService EventPlanPatrocinadorService;
	public static ClasificadorRecursoService ClasificadorRecursoService;
	public static PersonaService PersonaService;
	public static PlantillaTrabajoSocialActividadService PlantillaTrabajoSocialActividadService;
	public static PlantillaTrabajoSocialIndicadorService PlantillaTrabajoSocialIndicadorService;
	
	public static RespaldoTablaService RespaldoTablaService;
	
	static {
		// Services Seguridad
		VistaOperacionBasicoService = new VistaOperacionBasicoService();
		UsuarioService = new UsuarioService();
		PermisoSeguridadService = new PermisoSeguridadService();
		IconSclassService = new IconSclassService();
		VistaOperacionCustomService = new VistaOperacionCustomService();
		TablaService = new TablaService();
		OperacionService = new OperacionService();
		VistaService = new VistaService();
		AuditoriaService = new AuditoriaService();
		SesionService = new SesionService();
		NodoMenuService = new NodoMenuService();
		RolService = new RolService();
		MetodoDaoService = new MetodoDaoService();
		MensajeSistemaService = new MensajeSistemaService();
		SclassService = new SclassService();

		// Services Smile
		EventPlanPersonaService = new EventPlanPersonaService();
		FortalezaService = new FortalezaService();
		ActividadService = new ActividadService();
		IndicadorTsPlanActividadService = new IndicadorTsPlanActividadService();
		BeneficiarioFamiliarService = new BeneficiarioFamiliarService();
		ComentarioAlbumService = new ComentarioAlbumService();
		ColaboradorService = new ColaboradorService();
		TsPlanService = new TsPlanService();
		ClasificadorCapacitacionService = new ClasificadorCapacitacionService();
		IncidenciaTsPlanService = new IncidenciaTsPlanService();
		ProfesionService = new ProfesionService();
		ClasificadorReconocimientoService = new ClasificadorReconocimientoService();
		ClasificadorMotivoService = new ClasificadorMotivoService();
		RecursoService = new RecursoService();
		DirectorioService = new DirectorioService();
		IndicadorEventoPlanificadoService = new IndicadorEventoPlanificadoService();
		RequisitoService = new RequisitoService();
		CiudadService = new CiudadService();
		EtiqAlbumService = new EtiqAlbumService();
		SolicitudAyudaService = new SolicitudAyudaService();
		TrabajadorService = new TrabajadorService();
		TsPlanActividadRecursoService = new TsPlanActividadRecursoService();
		MultimediaAlbumService = new MultimediaAlbumService();
		VoluntarioFortalezaService = new VoluntarioFortalezaService();
		PreguntaService = new PreguntaService();
		TsPlanActividadService = new TsPlanActividadService();
		ClasificadorVoluntarioService = new ClasificadorVoluntarioService();
		EventoPlanificadoService = new EventoPlanificadoService();
		NotificacionUsuarioService = new NotificacionUsuarioService();
		EventPlanTareaVoluntarioService = new EventPlanTareaVoluntarioService();
		ComentarioCarteleraService = new ComentarioCarteleraService();
		ReconocimientoPersonaService = new ReconocimientoPersonaService();
		RedSocialService = new RedSocialService();
		TsPlanActividadTrabajadorService = new TsPlanActividadTrabajadorService();
		EventoService = new EventoService();
		CargoService = new CargoService();
		ValoresService = new ValoresService();
		IndicadorTsPlanService = new IndicadorTsPlanService();
		TrabajadorProfesionService = new TrabajadorProfesionService();
		ParticipacionService = new ParticipacionService();
		BancoService = new BancoService();
		FamiliarService = new FamiliarService();
		VolCapacitacionPlanificadaService = new VolCapacitacionPlanificadaService();
		TsPlanActividadVoluntarioService = new TsPlanActividadVoluntarioService();
		EventPlanTareaRecursoService = new EventPlanTareaRecursoService();
		AyudaService = new AyudaService();
		EventPlanTareaTrabajadorService = new EventPlanTareaTrabajadorService();
		PublicacionRedSocialService = new PublicacionRedSocialService();
		SolicitudAyudaRecursoService = new SolicitudAyudaRecursoService();
		AlbumService = new AlbumService();
		CapacitacionPlanificadaService = new CapacitacionPlanificadaService();
		RequisitoAyudaService = new RequisitoAyudaService();
		PreguntaClasificadaService = new PreguntaClasificadaService();
		BeneficiarioService = new BeneficiarioService();
		VoluntarioClasificadoService = new VoluntarioClasificadoService();
		UnidadMedidaService = new UnidadMedidaService();
		VoluntarioService = new VoluntarioService();
		TrabajadorFortalezaService = new TrabajadorFortalezaService();
		PadrinoService = new PadrinoService();
		CarteleraService = new CarteleraService();
		RedSocialOrganizacionService = new RedSocialOrganizacionService();
		EtiqCarteleraService = new EtiqCarteleraService();
		VoluntarioProfesionService = new VoluntarioProfesionService();
		OrganizacionService = new OrganizacionService();
		EventPlanTareaService = new EventPlanTareaService();
		MotivoService = new MotivoService();
		IndicadorService = new IndicadorService();
		ClasificadorEventoService = new ClasificadorEventoService();
		TrabajoSocialService = new TrabajoSocialService();
		TareaService = new TareaService();
		PlantillaEventoIndicadorService = new PlantillaEventoIndicadorService();
		ClasificadorTrabajoSocialService = new ClasificadorTrabajoSocialService();
		EventoFavoritoUsuarioService = new EventoFavoritoUsuarioService();
		TsPlanPersonaService = new TsPlanPersonaService();
		RespaldoService = new RespaldoService();
		CapacitacionService = new CapacitacionService();
		ConfiguracionService = new ConfiguracionService();
		ParentescoService = new ParentescoService();
		DonativoRecursoService = new DonativoRecursoService();
		EstudioSocioEconomicoService = new EstudioSocioEconomicoService();
		EtiqTsPlanificadoService = new EtiqTsPlanificadoService();
		CuentaBancariaService = new CuentaBancariaService();
		ClasificadorTareaService = new ClasificadorTareaService();
		PatrocinadorService = new PatrocinadorService();
		PlantillaEventoTareaService = new PlantillaEventoTareaService();
		ClasificadorSugerenciaService = new ClasificadorSugerenciaService();
		RequisitoParticipacionService = new RequisitoParticipacionService();
		DonativoCuentaBancariaService = new DonativoCuentaBancariaService();
		EtiquetaService = new EtiquetaService();
		ComunidadService = new ComunidadService();
		FrecuenciaAporteService = new FrecuenciaAporteService();
		InteraccionPortalService = new InteraccionPortalService();
		ClasificadorActividadService = new ClasificadorActividadService();
		DifusionService = new DifusionService();
		ClasificadorPreguntaService = new ClasificadorPreguntaService();
		IncidenciaEventoPlanService = new IncidenciaEventoPlanService();
		ContactoPortalService = new ContactoPortalService();
		EtiqEventoPlanificadoService = new EtiqEventoPlanificadoService();
		EstadoService = new EstadoService();
		MultimediaService = new MultimediaService();
		IndicadorEventoPlanTareaService = new IndicadorEventoPlanTareaService();
		EventPlanPatrocinadorService = new EventPlanPatrocinadorService();
		ClasificadorRecursoService = new ClasificadorRecursoService();
		PersonaService = new PersonaService();
		RespaldoTablaService = new RespaldoTablaService();
		PlantillaTrabajoSocialActividadService = new PlantillaTrabajoSocialActividadService();
		PlantillaTrabajoSocialIndicadorService = new PlantillaTrabajoSocialIndicadorService();
	}
}
