package ve.smile.consume.services;

import ve.smile.consume.services.FortalezaService;
import ve.smile.seguridad.consume.services.PermisoSeguridadService;
import ve.smile.consume.services.ActividadService;
import ve.smile.consume.services.BeneficiarioFamiliarService;
import ve.smile.consume.services.ComentarioAlbumService;
import ve.smile.consume.services.TsPlanService;
import ve.smile.consume.services.ClasificadorCapacitacionService;
import ve.smile.consume.services.TipoVoluntarioService;
import ve.smile.seguridad.consume.services.DispositivoAndroidService;
import ve.smile.consume.services.ProfesionService;
import ve.smile.consume.services.TipoActividadService;
import ve.smile.consume.services.ClasificadorMotivoService;
import ve.smile.consume.services.RecursoService;
import ve.smile.consume.services.DirectorioService;
import ve.smile.consume.services.RequisitoService;
import ve.smile.consume.services.CiudadService;
import ve.smile.seguridad.consume.services.SclassService;
import ve.smile.consume.services.SolicitudAyudaService;
import ve.smile.consume.services.TrabajadorService;
import ve.smile.seguridad.consume.services.IconSclassService;
import ve.smile.consume.services.TsPlanActividadRecursoService;
import ve.smile.seguridad.consume.services.TablaService;
import ve.smile.consume.services.VoluntarioFortalezaService;
import ve.smile.consume.services.PreguntaService;
import ve.smile.consume.services.TsPlanActividadService;
import ve.smile.consume.services.ClasificadorVoluntarioService;
import ve.smile.consume.services.EventoPlanificadoService;
import ve.smile.consume.services.NotificacionUsuarioService;
import ve.smile.seguridad.consume.services.RolService;
import ve.smile.consume.services.EventPlanTareaVoluntarioService;
import ve.smile.seguridad.consume.services.VistaOperacionBasicoService;
import ve.smile.consume.services.RedSocialService;
import ve.smile.consume.services.TsPlanActividadTrabajadorService;
import ve.smile.consume.services.EventoService;
import ve.smile.seguridad.consume.services.VistaOperacionCustomService;
import ve.smile.consume.services.ComentarioTrabajoSocialService;
import ve.smile.consume.services.MetaService;
import ve.smile.consume.services.TrabajadorProfesionService;
import ve.smile.consume.services.ParticipacionService;
import ve.smile.consume.services.BancoService;
import ve.smile.consume.services.SugerenciaService;
import ve.smile.consume.services.TsPlanVoluntarioService;
import ve.smile.consume.services.FamiliarService;
import ve.smile.consume.services.VolCapacitacionPlanificadaService;
import ve.smile.consume.services.TsPlanActividadVoluntarioService;
import ve.smile.consume.services.EventPlanTareaRecursoService;
import ve.smile.consume.services.ClasificadorPersonaService;
import ve.smile.seguridad.consume.services.NodoMenuService;
import ve.smile.consume.services.AyudaService;
import ve.smile.consume.services.EventPlanTareaTrabajadorService;
import ve.smile.consume.services.TipoTrabajoSocialService;
import ve.smile.consume.services.MetaTsPlanService;
import ve.smile.consume.services.SolicitudAyudaRecursoService;
import ve.smile.consume.services.AlbumService;
import ve.smile.consume.services.CapacitacionPlanificadaService;
import ve.smile.consume.services.EventPlanVoluntarioService;
import ve.smile.consume.services.RequisitoAyudaService;
import ve.smile.consume.services.BeneficiarioService;
import ve.smile.consume.services.UnidadMedidaService;
import ve.smile.consume.services.TipoMotivoService;
import ve.smile.consume.services.MetaTsPlanActividadService;
import ve.smile.consume.services.TipoCapacitacionService;
import ve.smile.consume.services.TipoRecursoService;
import ve.smile.consume.services.VoluntarioService;
import ve.smile.consume.services.TrabajadorFortalezaService;
import ve.smile.consume.services.PadrinoService;
import ve.smile.consume.services.CarteleraService;
import ve.smile.consume.services.ComenEventoPlanificadoService;
import ve.smile.consume.services.RedSocialOrganizacionService;
import ve.smile.consume.services.TipoEventoService;
import ve.smile.consume.services.VoluntarioProfesionService;
import ve.smile.consume.services.OrganizacionService;
import ve.smile.consume.services.EventPlanTareaService;
import ve.smile.consume.services.MotivoService;
import ve.smile.consume.services.IndicadorService;
import ve.smile.consume.services.ClasificadorEventoService;
import ve.smile.consume.services.TrabajoSocialService;
import ve.smile.consume.services.TareaService;
import ve.smile.seguridad.consume.services.OperacionService;
import ve.smile.seguridad.consume.services.SesionService;
import ve.smile.seguridad.consume.services.MetodoDaoService;
import ve.smile.consume.services.ClasificadorTrabajoSocialService;
import ve.smile.consume.services.EventoFavoritoUsuarioService;
import ve.smile.consume.services.CapacitacionService;
import ve.smile.consume.services.ConfiguracionService;
import ve.smile.consume.services.DonativoRecursoService;
import ve.smile.seguridad.consume.services.UsuarioService;
import ve.smile.consume.services.EstudioSocioEconomicoService;
import ve.smile.consume.services.NotificacionService;
import ve.smile.consume.services.EtiqTsPlanificadoService;
import ve.smile.consume.services.CuentaBancariaService;
import ve.smile.consume.services.ClasificadorTareaService;
import ve.smile.consume.services.PatrocinadorService;
import ve.smile.consume.services.ClasificadorSugerenciaService;
import ve.smile.consume.services.RequisitoParticipacionService;
import ve.smile.consume.services.DonativoCuentaBancariaService;
import ve.smile.consume.services.EtiquetaService;
import ve.smile.consume.services.ComunidadService;
import ve.smile.consume.services.FrecuenciaAporteService;
import ve.smile.consume.services.ClasificadorActividadService;
import ve.smile.consume.services.ClasificadorPreguntaService;
import ve.smile.consume.services.CarteleraEtiquetaService;
import ve.smile.consume.services.EtiqEventoPlanificadoService;
import ve.smile.seguridad.consume.services.MensajeSistemaService;
import ve.smile.consume.services.TipoPreguntaService;
import ve.smile.consume.services.EstadoService;
import ve.smile.consume.services.MetaEventPlanificadoTareaService;
import ve.smile.consume.services.MultimediaService;
import ve.smile.consume.services.MetaEventPlanificadoService;
import ve.smile.consume.services.ParentezcoService;
import ve.smile.seguridad.consume.services.VistaService;
import ve.smile.seguridad.consume.services.AuditoriaService;
import ve.smile.consume.services.TipoTareaService;
import ve.smile.consume.services.EventPlanPatrocinadorService;
import ve.smile.consume.services.ClasificadorRecursoService;
import ve.smile.consume.services.PersonaService;

public class S {

	public static FortalezaService FortalezaService;
	public static PermisoSeguridadService PermisoSeguridadService;
	public static ActividadService ActividadService;
	public static BeneficiarioFamiliarService BeneficiarioFamiliarService;
	public static ComentarioAlbumService ComentarioAlbumService;
	public static TsPlanService TsPlanService;
	public static ClasificadorCapacitacionService ClasificadorCapacitacionService;
	public static TipoVoluntarioService TipoVoluntarioService;
	public static DispositivoAndroidService DispositivoAndroidService;
	public static ProfesionService ProfesionService;
	public static TipoActividadService TipoActividadService;
	public static ClasificadorMotivoService ClasificadorMotivoService;
	public static RecursoService RecursoService;
	public static DirectorioService DirectorioService;
	public static RequisitoService RequisitoService;
	public static CiudadService CiudadService;
	public static SclassService SclassService;
	public static SolicitudAyudaService SolicitudAyudaService;
	public static TrabajadorService TrabajadorService;
	public static IconSclassService IconSclassService;
	public static TsPlanActividadRecursoService TsPlanActividadRecursoService;
	public static TablaService TablaService;
	public static VoluntarioFortalezaService VoluntarioFortalezaService;
	public static PreguntaService PreguntaService;
	public static TsPlanActividadService TsPlanActividadService;
	public static ClasificadorVoluntarioService ClasificadorVoluntarioService;
	public static EventoPlanificadoService EventoPlanificadoService;
	public static NotificacionUsuarioService NotificacionUsuarioService;
	public static RolService RolService;
	public static EventPlanTareaVoluntarioService EventPlanTareaVoluntarioService;
	public static VistaOperacionBasicoService VistaOperacionBasicoService;
	public static RedSocialService RedSocialService;
	public static TsPlanActividadTrabajadorService TsPlanActividadTrabajadorService;
	public static EventoService EventoService;
	public static VistaOperacionCustomService VistaOperacionCustomService;
	public static ComentarioTrabajoSocialService ComentarioTrabajoSocialService;
	public static MetaService MetaService;
	public static TrabajadorProfesionService TrabajadorProfesionService;
	public static ParticipacionService ParticipacionService;
	public static BancoService BancoService;
	public static SugerenciaService SugerenciaService;
	public static TsPlanVoluntarioService TsPlanVoluntarioService;
	public static FamiliarService FamiliarService;
	public static VolCapacitacionPlanificadaService VolCapacitacionPlanificadaService;
	public static TsPlanActividadVoluntarioService TsPlanActividadVoluntarioService;
	public static EventPlanTareaRecursoService EventPlanTareaRecursoService;
	public static ClasificadorPersonaService ClasificadorPersonaService;
	public static NodoMenuService NodoMenuService;
	public static AyudaService AyudaService;
	public static EventPlanTareaTrabajadorService EventPlanTareaTrabajadorService;
	public static TipoTrabajoSocialService TipoTrabajoSocialService;
	public static MetaTsPlanService MetaTsPlanService;
	public static SolicitudAyudaRecursoService SolicitudAyudaRecursoService;
	public static AlbumService AlbumService;
	public static CapacitacionPlanificadaService CapacitacionPlanificadaService;
	public static EventPlanVoluntarioService EventPlanVoluntarioService;
	public static RequisitoAyudaService RequisitoAyudaService;
	public static BeneficiarioService BeneficiarioService;
	public static UnidadMedidaService UnidadMedidaService;
	public static TipoMotivoService TipoMotivoService;
	public static MetaTsPlanActividadService MetaTsPlanActividadService;
	public static TipoCapacitacionService TipoCapacitacionService;
	public static TipoRecursoService TipoRecursoService;
	public static VoluntarioService VoluntarioService;
	public static TrabajadorFortalezaService TrabajadorFortalezaService;
	public static PadrinoService PadrinoService;
	public static CarteleraService CarteleraService;
	public static ComenEventoPlanificadoService ComenEventoPlanificadoService;
	public static RedSocialOrganizacionService RedSocialOrganizacionService;
	public static TipoEventoService TipoEventoService;
	public static VoluntarioProfesionService VoluntarioProfesionService;
	public static OrganizacionService OrganizacionService;
	public static EventPlanTareaService EventPlanTareaService;
	public static MotivoService MotivoService;
	public static IndicadorService IndicadorService;
	public static ClasificadorEventoService ClasificadorEventoService;
	public static TrabajoSocialService TrabajoSocialService;
	public static TareaService TareaService;
	public static SesionService SesionService;
	public static MetodoDaoService MetodoDaoService;
	public static ClasificadorTrabajoSocialService ClasificadorTrabajoSocialService;
	public static EventoFavoritoUsuarioService EventoFavoritoUsuarioService;
	public static CapacitacionService CapacitacionService;
	public static ConfiguracionService ConfiguracionService;
	public static DonativoRecursoService DonativoRecursoService;
	public static UsuarioService UsuarioService;
	public static EstudioSocioEconomicoService EstudioSocioEconomicoService;
	public static NotificacionService NotificacionService;
	public static EtiqTsPlanificadoService EtiqTsPlanificadoService;
	public static CuentaBancariaService CuentaBancariaService;
	public static ClasificadorTareaService ClasificadorTareaService;
	public static PatrocinadorService PatrocinadorService;
	public static ClasificadorSugerenciaService ClasificadorSugerenciaService;
	public static RequisitoParticipacionService RequisitoParticipacionService;
	public static DonativoCuentaBancariaService DonativoCuentaBancariaService;
	public static EtiquetaService EtiquetaService;
	public static ComunidadService ComunidadService;
	public static FrecuenciaAporteService FrecuenciaAporteService;
	public static ClasificadorActividadService ClasificadorActividadService;
	public static ClasificadorPreguntaService ClasificadorPreguntaService;
	public static CarteleraEtiquetaService CarteleraEtiquetaService;
	public static EtiqEventoPlanificadoService EtiqEventoPlanificadoService;
	public static MensajeSistemaService MensajeSistemaService;
	public static TipoPreguntaService TipoPreguntaService;
	public static EstadoService EstadoService;
	public static MetaEventPlanificadoTareaService MetaEventPlanificadoTareaService;
	public static MultimediaService MultimediaService;
	public static MetaEventPlanificadoService MetaEventPlanificadoService;
	public static ParentezcoService ParentezcoService;
	public static VistaService VistaService;
	public static AuditoriaService AuditoriaService;
	public static TipoTareaService TipoTareaService;
	public static EventPlanPatrocinadorService EventPlanPatrocinadorService;
	public static ClasificadorRecursoService ClasificadorRecursoService;
	public static PersonaService PersonaService;
	public static OperacionService OperacionService;
	static {
	FortalezaService = new FortalezaService();
	PermisoSeguridadService = new PermisoSeguridadService();
	ActividadService = new ActividadService();
	BeneficiarioFamiliarService = new BeneficiarioFamiliarService();
	ComentarioAlbumService = new ComentarioAlbumService();
	TsPlanService = new TsPlanService();
	ClasificadorCapacitacionService = new ClasificadorCapacitacionService();
	TipoVoluntarioService = new TipoVoluntarioService();
	DispositivoAndroidService = new DispositivoAndroidService();
	ProfesionService = new ProfesionService();
	TipoActividadService = new TipoActividadService();
	ClasificadorMotivoService = new ClasificadorMotivoService();
	RecursoService = new RecursoService();
	DirectorioService = new DirectorioService();
	RequisitoService = new RequisitoService();
	CiudadService = new CiudadService();
	SclassService = new SclassService();
	SolicitudAyudaService = new SolicitudAyudaService();
	TrabajadorService = new TrabajadorService();
	IconSclassService = new IconSclassService();
	TsPlanActividadRecursoService = new TsPlanActividadRecursoService();
	TablaService = new TablaService();
	VoluntarioFortalezaService = new VoluntarioFortalezaService();
	PreguntaService = new PreguntaService();
	TsPlanActividadService = new TsPlanActividadService();
	ClasificadorVoluntarioService = new ClasificadorVoluntarioService();
	EventoPlanificadoService = new EventoPlanificadoService();
	NotificacionUsuarioService = new NotificacionUsuarioService();
	RolService = new RolService();
	EventPlanTareaVoluntarioService = new EventPlanTareaVoluntarioService();
	VistaOperacionBasicoService = new VistaOperacionBasicoService();
	RedSocialService = new RedSocialService();
	TsPlanActividadTrabajadorService = new TsPlanActividadTrabajadorService();
	EventoService = new EventoService();
	VistaOperacionCustomService = new VistaOperacionCustomService();
	ComentarioTrabajoSocialService = new ComentarioTrabajoSocialService();
	MetaService = new MetaService();
	TrabajadorProfesionService = new TrabajadorProfesionService();
	ParticipacionService = new ParticipacionService();
	BancoService = new BancoService();
	SugerenciaService = new SugerenciaService();
	TsPlanVoluntarioService = new TsPlanVoluntarioService();
	FamiliarService = new FamiliarService();
	VolCapacitacionPlanificadaService = new VolCapacitacionPlanificadaService();
	TsPlanActividadVoluntarioService = new TsPlanActividadVoluntarioService();
	EventPlanTareaRecursoService = new EventPlanTareaRecursoService();
	ClasificadorPersonaService = new ClasificadorPersonaService();
	NodoMenuService = new NodoMenuService();
	AyudaService = new AyudaService();
	EventPlanTareaTrabajadorService = new EventPlanTareaTrabajadorService();
	TipoTrabajoSocialService = new TipoTrabajoSocialService();
	MetaTsPlanService = new MetaTsPlanService();
	SolicitudAyudaRecursoService = new SolicitudAyudaRecursoService();
	AlbumService = new AlbumService();
	CapacitacionPlanificadaService = new CapacitacionPlanificadaService();
	EventPlanVoluntarioService = new EventPlanVoluntarioService();
	RequisitoAyudaService = new RequisitoAyudaService();
	BeneficiarioService = new BeneficiarioService();
	UnidadMedidaService = new UnidadMedidaService();
	TipoMotivoService = new TipoMotivoService();
	MetaTsPlanActividadService = new MetaTsPlanActividadService();
	TipoCapacitacionService = new TipoCapacitacionService();
	TipoRecursoService = new TipoRecursoService();
	VoluntarioService = new VoluntarioService();
	TrabajadorFortalezaService = new TrabajadorFortalezaService();
	PadrinoService = new PadrinoService();
	CarteleraService = new CarteleraService();
	ComenEventoPlanificadoService = new ComenEventoPlanificadoService();
	RedSocialOrganizacionService = new RedSocialOrganizacionService();
	TipoEventoService = new TipoEventoService();
	VoluntarioProfesionService = new VoluntarioProfesionService();
	OrganizacionService = new OrganizacionService();
	EventPlanTareaService = new EventPlanTareaService();
	MotivoService = new MotivoService();
	IndicadorService = new IndicadorService();
	ClasificadorEventoService = new ClasificadorEventoService();
	TrabajoSocialService = new TrabajoSocialService();
	TareaService = new TareaService();
	SesionService = new SesionService();
	MetodoDaoService = new MetodoDaoService();
	ClasificadorTrabajoSocialService = new ClasificadorTrabajoSocialService();
	EventoFavoritoUsuarioService = new EventoFavoritoUsuarioService();
	CapacitacionService = new CapacitacionService();
	ConfiguracionService = new ConfiguracionService();
	DonativoRecursoService = new DonativoRecursoService();
	UsuarioService = new UsuarioService();
	EstudioSocioEconomicoService = new EstudioSocioEconomicoService();
	NotificacionService = new NotificacionService();
	EtiqTsPlanificadoService = new EtiqTsPlanificadoService();
	CuentaBancariaService = new CuentaBancariaService();
	ClasificadorTareaService = new ClasificadorTareaService();
	PatrocinadorService = new PatrocinadorService();
	ClasificadorSugerenciaService = new ClasificadorSugerenciaService();
	RequisitoParticipacionService = new RequisitoParticipacionService();
	DonativoCuentaBancariaService = new DonativoCuentaBancariaService();
	EtiquetaService = new EtiquetaService();
	ComunidadService = new ComunidadService();
	FrecuenciaAporteService = new FrecuenciaAporteService();
	ClasificadorActividadService = new ClasificadorActividadService();
	ClasificadorPreguntaService = new ClasificadorPreguntaService();
	CarteleraEtiquetaService = new CarteleraEtiquetaService();
	EtiqEventoPlanificadoService = new EtiqEventoPlanificadoService();
	MensajeSistemaService = new MensajeSistemaService();
	TipoPreguntaService = new TipoPreguntaService();
	EstadoService = new EstadoService();
	MetaEventPlanificadoTareaService = new MetaEventPlanificadoTareaService();
	MultimediaService = new MultimediaService();
	MetaEventPlanificadoService = new MetaEventPlanificadoService();
	ParentezcoService = new ParentezcoService();
	VistaService = new VistaService();
	AuditoriaService = new AuditoriaService();
	TipoTareaService = new TipoTareaService();
	EventPlanPatrocinadorService = new EventPlanPatrocinadorService();
	ClasificadorRecursoService = new ClasificadorRecursoService();
	PersonaService = new PersonaService();
	OperacionService = new OperacionService();
	}
}
